[tool.poetry]
name = "cherrydb"
version = "0.1.0"
description = ""
authors = ["Parker J. Rule <parker.rule@tufts.edu>"]

[tool.poetry.dependencies]
python = "^3.10"
tomlkit = "^0.11.6"
msgpack = "^1.0.4"
httpx = "^0.23.3"
pydantic = "^1.10.4"
orjson = "^3.8.6"
shapely = "^2.0.1"
python-dateutil = "^2.8.2"
geopandas = "^0.12.2"
networkx = "^3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
black = "^23.1.0"
pytest-vcr = "^1.0.2"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
